WITH T as (
    SELECT 
        MONTH(START_DATE) as MONTH, CAR_ID, COUNT(*) AS RECORDS 
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE 
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
    GROUP BY 
        CAR_ID, MONTH(START_DATE)
)

SELECT 
    *
FROM 
    T 
WHERE 
    CAR_ID in (SELECT CAR_ID FROM T GROUP BY CAR_ID HAVING SUM(RECORDS)>=5) AND T.RECORDS>0 
ORDER BY 
    1, 2 DESC