-- 코드를 입력하세요
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' 
AND TO_CHAR(PUBLISHED_DATE, 'YYYYMMDD') >='20210101' 
AND TO_CHAR(PUBLISHED_DATE, 'YYYYMMDD') <='20211231'
ORDER BY PUBLISHED_DATE ASC